[pytest]
testpaths =
    vendor/spot-sdk/python/bosdyn-client/tests
    vendor/spot-sdk/python/bosdyn-mission/tests
pythonpath =
    vendor/spot-sdk/python/bosdyn-client/tests
    vendor/spot-sdk/python/bosdyn-mission/tests
    .
